Bug wrapper algorunner out of memory
kube-HPC/python-wrapper.hkube pull request #128
Opened 2024-08-08 12:27 UTC by Adir111

Added a method to run a thread that periodically sends a signal to indicate the wrapper is still alive.
Issue: kube-HPC/hkube#1975

2024-08-08 12:33 UTC, golanha requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/python-wrapper.hkube/128)* status: all files reviewed, 1 unresolved discussion (waiting on @Adir111)

___
*[`hkube_python_wrapper/wrapper/algorunner.py` line 422 at r1](https://reviewable.io/reviews/kube-HPC/python-wrapper.hkube/128#-O3lyWkX-cQtH89RNWyX:-O3lyWkX-cQtH89RNWyY:bqgn8kn) ([raw file](https://github.com/kube-HPC/python-wrapper.hkube/blob/df50fbd18e840fe6182acc14d4a0b6bb6b325929/hkube_python_wrapper/wrapper/algorunner.py#L422)):*
> ```Python
>             algorithmData = method(self._input, self._hkubeApi)
>             if not (self._stopped):
>                 self._done = True
> ```

Should be set to done before checknig for stopped or not



_Code quote:_
```Python
 self._done = True
```


<!-- Sent from Reviewable.io -->

2024-08-08 12:46 UTC, Adir111 reviewed
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/python-wrapper.hkube/128)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @golanha)

___
*[`hkube_python_wrapper/wrapper/algorunner.py` line 422 at r1](https://reviewable.io/reviews/kube-HPC/python-wrapper.hkube/128#-O3lyWkX-cQtH89RNWyX:-O3m0gXHDidrox1McJzQ:b-896fix) ([raw file](https://github.com/kube-HPC/python-wrapper.hkube/blob/df50fbd18e840fe6182acc14d4a0b6bb6b325929/hkube_python_wrapper/wrapper/algorunner.py#L422)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

Should be set to done before checknig for stopped or not
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-08 12:56 UTC, golanha approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/python-wrapper.hkube/128)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Adir111)



<!-- Sent from Reviewable.io -->

2024-08-21 07:37 UTC, golanha approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/python-wrapper.hkube/128)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Adir111)



<!-- Sent from Reviewable.io -->

2024-08-21 08:06 UTC, merged