Multi part
kube-HPC/python-wrapper.hkube pull request #24
Opened 2020-09-09 12:58 UTC by golanha

2020-09-10 07:16 UTC, NassiHarel requested changes
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/24)* status: all files reviewed, 7 unresolved discussions (waiting on @golanha)

___
*[hkube_python_wrapper/communication/DataServer.py, line 43 at r1](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/24#-MGqlDUIBP7XRZ4VNMSP:-MGqlDUIBP7XRZ4VNMSQ:b-95ip5z) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/7ed3535428c1f32664c4596949b0af151b66dd23/hkube_python_wrapper/communication/DataServer.py#L43)):*
> ```
> def createData
> ```
is this function in use?
___
*[hkube_python_wrapper/communication/zmq/ZMQRequest.py, line 18 at r1](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/24#-MGqrdm58mcPgHax5n4c:-MGqrdm58mcPgHax5n4d:bavsjxq) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/7ed3535428c1f32664c4596949b0af151b66dd23/hkube_python_wrapper/communication/zmq/ZMQRequest.py#L18)):*
> ```
> def invokeAdapter(self):
> ```
No more 'Are you there'?
___
*[hkube_python_wrapper/wrapper/data_adapter.py, line 45 at r1](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/24#-MGqnfCa87PqoKh2cco_:-MGqnfCa87PqoKh2ccoa:b-dfyeqq) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/7ed3535428c1f32664c4596949b0af151b66dd23/hkube_python_wrapper/wrapper/data_adapter.py#L45)):*
> ```
>  if (useCache is False):
>             self._storageCache = Cache(config.storage)
> ```
You don't want remove this?
___
*[hkube_python_wrapper/wrapper/data_adapter.py, line 136 at r1](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/24#-MGqnBhBBDNAn1kgPNEi:-MGqnBhBBDNAn1kgPNEj:b-7pzj41) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/7ed3535428c1f32664c4596949b0af151b66dd23/hkube_python_wrapper/wrapper/data_adapter.py#L136)):*
> ```
>  self._setToCache(cacheId, data, size)
> ```
What if data is an error?
___
*[hkube_python_wrapper/wrapper/data_adapter.py, line 152 at r1](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/24#-MGqfWrO1y2YVZlEkkgk:-MGqfWrO1y2YVZlEkkgl:b-oddduu) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/7ed3535428c1f32664c4596949b0af151b66dd23/hkube_python_wrapper/wrapper/data_adapter.py#L152)):*
> ```
> def _getFromPeer(self, options, dataPath):
>         tasks = options.get('tasks')
>         taskId = options.get('taskId')
> ```

Maybe we can change it here to always request tasks?
this will remove complexity and reduce the amount of code.
___
*[hkube_python_wrapper/wrapper/data_adapter.py, line 162 at r1](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/24#-MGqq5eg292mCIrm-uDX:-MGqq5eg292mCIrm-uDY:b-4l73t3) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/7ed3535428c1f32664c4596949b0af151b66dd23/hkube_python_wrapper/wrapper/data_adapter.py#L162)):*
> ```Python
>             results = []
>             for data in dataList:
>                 results.append(len(data), data)
> ```

This function has 3 errors...

1) `results.append(len(data), data)` will throw an error, use `(( ))` for tuple
2) you are not doing anything with `results`.
3) local variable 'responses' referenced before assignment
___
*[hkube_python_wrapper/wrapper/data_adapter.py, line 179 at r1](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/24#-MGqfvP56MQGcLBtCIlF:-MGqfvP56MQGcLBtCIlG:br0fua) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/7ed3535428c1f32664c4596949b0af151b66dd23/hkube_python_wrapper/wrapper/data_adapter.py#L179)):*
> ```
> return responses
> ```
this will throw an error...


<!-- Sent from Reviewable.io -->

2020-09-10 09:01 UTC, golanha reviewed
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/24)* status: 2 of 9 files reviewed, 9 unresolved discussions (waiting on @NassiHarel)

___
*[hkube_python_wrapper/communication/DataServer.py, line 43 at r1](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/24#-MGqlDUIBP7XRZ4VNMSP:-MGqsaNg2j7L-FhI-QAs:b-3gvayo) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/7ed3535428c1f32664c4596949b0af151b66dd23/hkube_python_wrapper/communication/DataServer.py#L43)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> def createData
> ```
is this function in use?
</blockquote></details>

Removing createData
___
*[hkube_python_wrapper/communication/zmq/ZMQRequest.py, line 18 at r1](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/24#-MGqrdm58mcPgHax5n4c:-MGqsmKX1l_orFfXReBs:b4vwyoy) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/7ed3535428c1f32664c4596949b0af151b66dd23/hkube_python_wrapper/communication/zmq/ZMQRequest.py#L18)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> def invokeAdapter(self):
> ```
No more 'Are you there'?
</blockquote></details>

Actually I removed it for POC. I'll put it back and let it be changed upon merge with yhiam
___
*[hkube_python_wrapper/wrapper/data_adapter.py, line 45 at r1](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/24#-MGqnfCa87PqoKh2cco_:-MGqtGsUDMt6OSzf6bM6:byn0i5e) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/7ed3535428c1f32664c4596949b0af151b66dd23/hkube_python_wrapper/wrapper/data_adapter.py#L45)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
>  if (useCache is False):
>             self._storageCache = Cache(config.storage)
> ```
You don't want remove this?
</blockquote></details>

Right, we spoke about this.
___
*[hkube_python_wrapper/wrapper/data_adapter.py, line 135 at r1](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/24#-MGqtWef1P7WnxVCgJEP:-MGqtWef1P7WnxVCgJEQ:b-1cebwe) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/7ed3535428c1f32664c4596949b0af151b66dd23/hkube_python_wrapper/wrapper/data_adapter.py#L135)):*
> ```
> ataFromPeerOrStorag
> ```
___
*[hkube_python_wrapper/wrapper/data_adapter.py, line 136 at r1](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/24#-MGqnBhBBDNAn1kgPNEi:-MGqu2XfALcwrGeuI6NK:b-j49fqv) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/7ed3535428c1f32664c4596949b0af151b66dd23/hkube_python_wrapper/wrapper/data_adapter.py#L136)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
>  self._setToCache(cacheId, data, size)
> ```
What if data is an error?
</blockquote></details>

right, I'll put in cache only if no error
___
*[hkube_python_wrapper/wrapper/data_adapter.py, line 152 at r1](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/24#-MGqfWrO1y2YVZlEkkgk:-MGquEdp9bQRsvKP62QB:b-eirccc) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/7ed3535428c1f32664c4596949b0af151b66dd23/hkube_python_wrapper/wrapper/data_adapter.py#L152)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> def _getFromPeer(self, options, dataPath):
>         tasks = options.get('tasks')
>         taskId = options.get('taskId')
> ```

Maybe we can change it here to always request tasks?
this will remove complexity and reduce the amount of code.


</blockquote></details>

Yes, I thought so too
___
*[hkube_python_wrapper/wrapper/data_adapter.py, line 158 at r1](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/24#-MGquikf8dKn8faKJ9b_:-MGquikf8dKn8faKJ9ba:bxaexbu) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/7ed3535428c1f32664c4596949b0af151b66dd23/hkube_python_wrapper/wrapper/data_adapter.py#L158)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> isLocal(host, port)):
>             dataList = self._dataServer.getDataByTaskId(taskId, tasks)
>             results = []
>             for data in dataList:
>                 results.append(len(data), data)
> ```
</details>

___
*[hkube_python_wrapper/wrapper/data_adapter.py, line 162 at r1](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/24#-MGqq5eg292mCIrm-uDX:-MGquYq74QwMTp2JQByI:b-4fonwj) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/7ed3535428c1f32664c4596949b0af151b66dd23/hkube_python_wrapper/wrapper/data_adapter.py#L162)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

This function has 3 errors...

1) `results.append(len(data), data)` will throw an error, use `(( ))` for tuple
2) you are not doing anything with `results`.
3) local variable 'responses' referenced before assignment
</blockquote></details>

correcting
___
*[hkube_python_wrapper/wrapper/data_adapter.py, line 179 at r1](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/24#-MGqfvP56MQGcLBtCIlF:-MGqugKY7GgzraxzwIe2:bo5hytf) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/7ed3535428c1f32664c4596949b0af151b66dd23/hkube_python_wrapper/wrapper/data_adapter.py#L179)):*
> correcting
correcting


<!-- Sent from Reviewable.io -->

2020-09-10 09:09 UTC, NassiHarel requested changes
> Reviewed 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/24)* status: all files reviewed, 8 unresolved discussions (waiting on @golanha and @NassiHarel)

___
*[hkube_python_wrapper/communication/DataRequest.py, line 15 at r2](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/24#-MGrGL8I4dOwm1ZnTdiO:-MGrGL8I4dOwm1ZnTdiP:bzibqnj) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/9edddc17deb0c36b07515cf22785fadbfe325e70/hkube_python_wrapper/communication/DataRequest.py#L15)):*
> ```
>  u'dataPath': reqDetails.get('dataPath')
> ```
Do we need this?
___
*[hkube_python_wrapper/wrapper/data_adapter.py, line 139 at r2](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/24#-MGrG-uw58shRxyTgQAE:-MGrG-uw58shRxyTgQAF:b73e9gm) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/9edddc17deb0c36b07515cf22785fadbfe325e70/hkube_python_wrapper/wrapper/data_adapter.py#L139)):*
> ```
> self._setToCache(cacheId, data, size)
> ```
But you put it already in cache above....
___
*[hkube_python_wrapper/wrapper/data_adapter.py, line 170 at r2](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/24#-MGrGi9e1TC5jmLzaS4N:-MGrGi9e1TC5jmLzaS4O:b-k9enwp) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/9edddc17deb0c36b07515cf22785fadbfe325e70/hkube_python_wrapper/wrapper/data_adapter.py#L170)):*
> ```
> 'dataPath': dataPath,
> ```
Do we need this?


<!-- Sent from Reviewable.io -->

2020-09-10 09:23 UTC, NassiHarel requested changes
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/24)* status: all files reviewed, 9 unresolved discussions (waiting on @golanha and @NassiHarel)

___
*[hkube_python_wrapper/wrapper/data_adapter.py, line 162 at r2](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/24#-MGrJptr5m2UtVDroIro:-MGrJptr5m2UtVDroIrp:bz1cugz) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/9edddc17deb0c36b07515cf22785fadbfe325e70/hkube_python_wrapper/wrapper/data_adapter.py#L162)):*
> ```
>  responses.append((len(data), data))
> ```
This data should be decoded


<!-- Sent from Reviewable.io -->

2020-09-13 11:07 UTC, NassiHarel approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/24#-:-MH68ZPY7bvOIWa8XMlF:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @yehiyam)



<!-- Sent from Reviewable.io -->

2020-09-13 11:14 UTC, yehiyam approved these changes
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/24)* status: all files reviewed, 2 unresolved discussions



<!-- Sent from Reviewable.io -->

2020-09-13 11:15 UTC, merged