Gevent streaming
kube-HPC/python-wrapper.hkube pull request #36
Opened 2020-11-03 09:58 UTC by golanha

2020-11-05 11:02 UTC, NassiHarel requested changes
> Reviewed 9 of 17 files at r1, 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36)* status: 10 of 17 files reviewed, 9 unresolved discussions (waiting on @golanha and @NassiHarel)

___
*[hkube_python_wrapper/communication/streaming/MessageProducer.py, line 9 at r2](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLN36XrDHhXqvNZ7w9r:-MLN36XrDHhXqvNZ7w9s:bev4lr3) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/3740a54cbc799c0f6ade60b8ba06efb80081a3e1/hkube_python_wrapper/communication/streaming/MessageProducer.py#L9)):*
> ```Python
> RESPONSE_CACHE = 2000
> ```

please do integration tests.
Try to run a batch pipeline, then a stream pipeline, then again batch....
 you will see something is broken.
___
*[hkube_python_wrapper/communication/zmq/streaming/ZMQProducer.py, line 27 at r2](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLMzpSm7ubeU8yYLVeT:-MLMzpSm7ubeU8yYLVeU:b-bj76em) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/3740a54cbc799c0f6ade60b8ba06efb80081a3e1/hkube_python_wrapper/communication/zmq/streaming/ZMQProducer.py#L27)):*
> ```
> class WorkerQueue
> ```
Maybe split all classes here into files
___
*[hkube_python_wrapper/communication/zmq/streaming/ZMQProducer.py, line 192 at r2](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLMzlbn6PlFQc4UxZ-j:-MLMzlbn6PlFQc4UxZ-k:b-fgvrip) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/3740a54cbc799c0f6ade60b8ba06efb80081a3e1/hkube_python_wrapper/communication/zmq/streaming/ZMQProducer.py#L192)):*
> ```
> # if __name__ == "__main__":
> ```
remove comments
___
*[hkube_python_wrapper/config/config.py, line 34 at r2](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLMhbpg-8IUDxM-7v08:-MLMhbpg-8IUDxM-7v09:bqgmblc) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/3740a54cbc799c0f6ade60b8ba06efb80081a3e1/hkube_python_wrapper/config/config.py#L34)):*
> ```
> "port": os.environ.get('STREAMING_DISCOVERY_PORT', 9021),
> ```
Change to 9022, the ping is now 9021
___
*[hkube_python_wrapper/config/config.py, line 43 at r2](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLN-5J107IAQOZMuq6o:-MLN-5J107IAQOZMuq6p:b-7ndt9w) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/3740a54cbc799c0f6ade60b8ba06efb80081a3e1/hkube_python_wrapper/config/config.py#L43)):*
> ```
> "isStatefull": os.environ.get('IS_STATEFULL')
> ```
unused
___
*[hkube_python_wrapper/config/config.py, line 49 at r2](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLN-7erERUZaQr8ukY1:-MLN-7erERUZaQr8ukY2:b-j0p0hf) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/3740a54cbc799c0f6ade60b8ba06efb80081a3e1/hkube_python_wrapper/config/config.py#L49)):*
> ```
>  'bson'),
> ```
Why?
___
*[hkube_python_wrapper/wrapper/algorunner.py, line 29 at r2](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLN1rHC7NdutJ-uTNTX:-MLN1rHC7NdutJ-uTNTY:b-4tumvc) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/3740a54cbc799c0f6ade60b8ba06efb80081a3e1/hkube_python_wrapper/wrapper/algorunner.py#L29)):*
> ```
> self._events = Events()
> ```
unused
___
*[hkube_python_wrapper/wrapper/algorunner.py, line 303 at r2](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLN-ydG-IpATL8cx3XV:-MLN-ydG-IpATL8cx3XW:b-awxqk0) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/3740a54cbc799c0f6ade60b8ba06efb80081a3e1/hkube_python_wrapper/wrapper/algorunner.py#L303)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>             topSpan = options.get(
>                 'spanId') if options else self._input.get('spanId')
>             span = Tracer.instance.create_span(
>                 "start", topSpan, jobId, taskId, nodeName)
> ```
</details>

this is an ugly format...
___
*[hkube_python_wrapper/wrapper/algorunner.py, line 402 at r2](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLN0CsnDZo4ZIghCMnF:-MLN0CsnDZo4ZIghCMnG:bgwkay6) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/3740a54cbc799c0f6ade60b8ba06efb80081a3e1/hkube_python_wrapper/wrapper/algorunner.py#L402)):*
> ```
>             self._wsc.shutDown()
>             self._wsc.shutDown()
> ```
duplicate


<!-- Sent from Reviewable.io -->

2020-11-05 14:43 UTC, yehiyam requested changes
> Reviewed 1 of 17 files at r1, 3 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36)* status: 14 of 17 files reviewed, 29 unresolved discussions (waiting on @golanha and @yehiyam)

___
*[hkube_python_wrapper/codeApi/hkube_api.py, line 49 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLNlqrO7dGDFDVl9JHK:-MLNlqrO7dGDFDVl9JHL:b-bcqpry) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/063e656a872549514587c3336acdfd1679ea031c/hkube_python_wrapper/codeApi/hkube_api.py#L49)):*
> ```
> listenr
> ```
Typo
___
*[hkube_python_wrapper/communication/streaming/MessageListener.py, line 23 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLNmGPmA8kfUCr1QwUt:-MLNmGPn812xP1dIxNim:b-qj7l68) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/063e656a872549514587c3336acdfd1679ea031c/hkube_python_wrapper/communication/streaming/MessageListener.py#L23)):*
> ```Python
>         start = time.time()
>         decodedMsg = self._encoding.decode(header=header, value=msg)
>         for listener in self.messageListeners:
> ```

is there more than one listener?
___
*[hkube_python_wrapper/communication/streaming/MessageProducer.py, line 35 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLNddm811qouZ3kMRwZ:-MLNddm811qouZ3kMRw_:bvpqdq0) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/063e656a872549514587c3336acdfd1679ea031c/hkube_python_wrapper/communication/streaming/MessageProducer.py#L35)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
>         def sendStatisticsEvery(interval):
>             while (self.active):
>                 self.sendStatistics()
>                 time.sleep(interval)
>         if (self.nodeNames):
>             runThread = Thread(name="Statistics", target=sendStatisticsEvery, args=[statisticsInterval])
>             runThread.start()
> ```
</details>

it is better to create the thread with `daemon=True`
use `from hkube_python_wrapper.util.timerImpl import Timer` as the timer implementation
___
*[hkube_python_wrapper/communication/streaming/MessageProducer.py, line 42 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLNeiAE6gnqTs_IbbN7:-MLNeiAE6gnqTs_IbbN8:bmg3fup) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/063e656a872549514587c3336acdfd1679ea031c/hkube_python_wrapper/communication/streaming/MessageProducer.py#L42)):*
> ```Python
> 
>     def responseAccumulator(self, response, consumerType):
>         decodedResponse = self._encoding.decode(value=response, plainEncode=True)
> ```

Is there anything else in the response besides `duration`?
___
*[hkube_python_wrapper/communication/streaming/MessageProducer.py, line 47 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLNeveU5xJvYjATbcEK:-MLNeveU5xJvYjATbcEL:b6ksl4l) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/063e656a872549514587c3336acdfd1679ea031c/hkube_python_wrapper/communication/streaming/MessageProducer.py#L47)):*
> ```
>         self.responsesCache[consumerType].append(float(duration))
>         if (len(self.responsesCache) > RESPONSE_CACHE):
>             self.responsesCache.pop(0)
> ```
Why not encapsulate this logic (fixed size FIFO array) in a class?
___
*[hkube_python_wrapper/communication/streaming/MessageProducer.py, line 73 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLNgm0OAqcbHwyHzfQx:-MLNgm0P0eoVUyq637-C:b-c8w7wz) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/063e656a872549514587c3336acdfd1679ea031c/hkube_python_wrapper/communication/streaming/MessageProducer.py#L73)):*
> ```Python
>             listener(statistics)
>         for singleNodeStatisticsForPrint in statistics:
>             singleNodeStatisticsForPrint['durations'] = singleNodeStatisticsForPrint['durations'][:10]
> ```

You are overwriting the original `statistics`
Is that what you wanted?
___
*[hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, line 28 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLNk8576QYjLT-T-e_q:-MLNk8576QYjLT-T-e_r:bpk09kt) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/063e656a872549514587c3336acdfd1679ea031c/hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py#L28)):*
> ```Python
>            connected to the Paranoid Pirate queue"""
>         worker = context.socket(zmq.DEALER)  # DEALER
>         identity = ('id' + str(randint(0, 0x10000)) + '-' + str(randint(0, 0x10000))).encode()
> ```

why not use GUID or something standard? 
___
*[hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, line 30 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLNnLiF0DLwR_yQlBlI:-MLNnLiF0DLwR_yQlBlJ:b-p8tgbm) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/063e656a872549514587c3336acdfd1679ea031c/hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py#L30)):*
> ```Python
>         identity = ('id' + str(randint(0, 0x10000)) + '-' + str(randint(0, 0x10000))).encode()
>         worker.setsockopt(zmq.IDENTITY, identity)
>         poller.register(worker, zmq.POLLIN)
> ```

since you have only one socket you can poll directly on the socket. no need for Poller
___
*[hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, line 33 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLNkMwaEZb36pmQDkud:-MLNkMwaEZb36pmQDkue:bq24gcj) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/063e656a872549514587c3336acdfd1679ea031c/hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py#L33)):*
> ```Python
>         worker.connect(remoteAddress)
>         print("zmq listener connecting to " + remoteAddress)
>         worker.send_multipart([PPP_READY, msgpack.packb(self.consumerType)])
> ```

consumerType is nodeName?
___
*[hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, line 63 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLNl1hu7s9mGZyV9Nd1:-MLNl1hu7s9mGZyV9Nd2:b-h9m1kq) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/063e656a872549514587c3336acdfd1679ea031c/hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py#L63)):*
> ```Python
>                         print(e)
>                 if not frames:
>                     break  # Interrupted
> ```

break to where? exit the entire `while self.active:` loop? This will stop the Thread and there is no way to recover from this
___
*[hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, line 66 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLNlAqPDYm9j6Lt9F7Z:-MLNlAqPDYm9j6Lt9F7_:b-1qpwnl) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/063e656a872549514587c3336acdfd1679ea031c/hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py#L66)):*
> ```Python
> 
>                 if len(frames) == 2:
>                     # Simulate various problems, after a few cycles
> ```

delete comment and `cycles` variable
___
*[hkube_python_wrapper/communication/zmq/streaming/ZMQProducer.py, line 31 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLNo3MB2SfFcVdTwJGY:-MLNo3MB2SfFcVdTwJGZ:bb752ax) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/063e656a872549514587c3336acdfd1679ea031c/hkube_python_wrapper/communication/zmq/streaming/ZMQProducer.py#L31)):*
> ```Python
>         self.queues = {}
>         for consumberType in consumerTypes:
>             self.queues[consumberType] = OrderedDict()
> ```

Typo
___
*[hkube_python_wrapper/communication/zmq/streaming/ZMQProducer.py, line 45 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLNoKAW-CIAlHNu-54F:-MLNoKAW-CIAlHNu-54G:b-cjuv1r) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/063e656a872549514587c3336acdfd1679ea031c/hkube_python_wrapper/co [...]

2020-11-05 14:53 UTC, yehiyam reviewed
You need to test that all the threads that you open will allow the process to exit

> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-:-MLNtNsX4Y8LKz1kxhci:bk9y8qz)* status: 14 of 17 files reviewed, 29 unresolved discussions (waiting on @golanha)



<!-- Sent from Reviewable.io -->

2020-11-09 11:19 UTC, golanha reviewed
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36)* status: 9 of 19 files reviewed, 29 unresolved discussions (waiting on @golanha, @NassiHarel, and @yehiyam)

___
*[hkube_python_wrapper/codeApi/hkube_api.py, line 49 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLNlqrO7dGDFDVl9JHK:-MLS4eudC7Z05LCoH8cj:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/063e656a872549514587c3336acdfd1679ea031c/hkube_python_wrapper/codeApi/hkube_api.py#L49)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

> ```
> listenr
> ```
Typo
</blockquote></details>

Done.
___
*[hkube_python_wrapper/communication/streaming/MessageListener.py, line 23 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLNmGPmA8kfUCr1QwUt:-MLg5kLgCsTgwv21KOs9:bx3ika6) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/063e656a872549514587c3336acdfd1679ea031c/hkube_python_wrapper/communication/streaming/MessageListener.py#L23)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

is there more than one listener?
</blockquote></details>

Hkube api is the only listener registering to MessageListener.
(HkubeAPI diffuses the message to any number listeners registered to hkube )
___
*[hkube_python_wrapper/communication/streaming/MessageProducer.py, line 42 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLNeiAE6gnqTs_IbbN7:-MLa_d94DPV5aoMkWb1b:b-c4s1oh) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/063e656a872549514587c3336acdfd1679ea031c/hkube_python_wrapper/communication/streaming/MessageProducer.py#L42)):*
> ```
>  self.responseCount[consumerType] += 1
> ```
No
___
*[hkube_python_wrapper/communication/streaming/MessageProducer.py, line 47 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLNeveU5xJvYjATbcEK:-MLgAttAEkId8DKLKsuK:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/063e656a872549514587c3336acdfd1679ea031c/hkube_python_wrapper/communication/streaming/MessageProducer.py#L47)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

> ```
>         self.responsesCache[consumerType].append(float(duration))
>         if (len(self.responsesCache) > RESPONSE_CACHE):
>             self.responsesCache.pop(0)
> ```
Why not encapsulate this logic (fixed size FIFO array) in a class?
</blockquote></details>

Done.
___
*[hkube_python_wrapper/communication/streaming/MessageProducer.py, line 73 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLNgm0OAqcbHwyHzfQx:-MLabOeFAZ0JnNZGpOU0:b-anirgd) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/063e656a872549514587c3336acdfd1679ea031c/hkube_python_wrapper/communication/streaming/MessageProducer.py#L73)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

You are overwriting the original `statistics`
Is that what you wanted?
</blockquote></details>

statistics  and its elements are a local variables which are not used after print.
___
*[hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, line 28 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLNk8576QYjLT-T-e_q:-MLgFkiK-lmoz3o9hSRV:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/063e656a872549514587c3336acdfd1679ea031c/hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py#L28)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

why not use GUID or something standard? 
</blockquote></details>

Done.
___
*[hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, line 30 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLNnLiF0DLwR_yQlBlI:-MLgJS6H9XNgDXgPgchP:bkpxc4r) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/063e656a872549514587c3336acdfd1679ea031c/hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py#L30)):*
> ```
> poller.register(worker, zmq.POLLIN)
> ```
Done
___
*[hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, line 33 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLNkMwaEZb36pmQDkud:-MLgJgZS4N7eJidYF8Gl:b-fqd47n) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/063e656a872549514587c3336acdfd1679ea031c/hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py#L33)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

consumerType is nodeName?
</blockquote></details>

Yes in this layer still uses communication related names.
___
*[hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, line 63 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLNl1hu7s9mGZyV9Nd1:-MLgN1WoAmMnVSm9hmU7:bd8vyuz) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/063e656a872549514587c3336acdfd1679ea031c/hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py#L63)):*
> ```
>  if not frames:
> ```
I will throw exception in case listener is still suppose to be active.
___
*[hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, line 66 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLNlAqPDYm9j6Lt9F7Z:-MLgNy-s-S0e00l-VWAI:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/063e656a872549514587c3336acdfd1679ea031c/hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py#L66)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

delete comment and `cycles` variable
</blockquote></details>

Done.
___
*[hkube_python_wrapper/communication/zmq/streaming/ZMQProducer.py, line 27 at r2](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLMzpSm7ubeU8yYLVeT:-MLNR35P7s6Q-ONcmtCT:bgbf8g6) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/3740a54cbc799c0f6ade60b8ba06efb80081a3e1/hkube_python_wrapper/communication/zmq/streaming/ZMQProducer.py#L27)):*
> WorkerQueue
Since all these classes are made for the producer mechanism only,  i prefer to keep them internal.
___
*[hkube_python_wrapper/communication/zmq/streaming/ZMQProducer.py, line 192 at r2](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLMzlbn6PlFQc4UxZ-j:-MLNRiOVAveBZZNTW6J3:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/3740a54cbc799c0f6ade60b8ba06efb80081a3e1/hkube_python_wrapper/communication/zmq/streaming/ZMQProducer.py#L192)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> # if __name__ == "__main__":
> ```
remove comments
</blockquote></details>

Done.
___
*[hkube_python_wrapper/communication/zmq/streaming/ZMQProducer.py, line 31 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLNo3MB2SfFcVdTwJGY:-MLgORpW9kP6F7JcdyS5:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/063e656a872549514587c3336acdfd1679ea031c/hkube_python_wrapper/communication/zmq/streaming/ZMQProducer.py#L31)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Typo
</blockquote></details>

Done.
___
*[hkube_python_wrapper/communication/zmq/streaming/ZMQProducer.py, line 45 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLNoKAW-CIAlHNu-54F:-MLgOzLcEH_XArSgJfDn:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/063e656a872549514587c3336acdfd1679ea031c/hkube_python_wrapper/communication/zmq/streaming/ZMQProducer.py#L45)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

> ```
> cunsumerType
> ```
Typo
</blockquote></details>

Done.
___
*[hkube_python_wrapper/communication/zmq/streaming/ZMQProducer.py, line 54 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLNo_dDB2IHmth312S5:-MLgQNXj-WiEWbGnm9fq:b-j84mcq) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/063e656a872549514587c3336acd [...]

2020-11-09 13:39 UTC, golanha reviewed
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36)* status: 8 of 20 files reviewed, 29 unresolved discussions (waiting on @golanha, @NassiHarel, and @yehiyam)

___
*[hkube_python_wrapper/communication/streaming/MessageProducer.py, line 9 at r2](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLN36XrDHhXqvNZ7w9r:-MLhDjobDgkDFDc4DolZ:b-teysft) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/3740a54cbc799c0f6ade60b8ba06efb80081a3e1/hkube_python_wrapper/communication/streaming/MessageProducer.py#L9)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

please do integration tests.
Try to run a batch pipeline, then a stream pipeline, then again batch....
 you will see something is broken.
</blockquote></details>

Fixed and added tests
___
*[hkube_python_wrapper/communication/streaming/MessageProducer.py, line 35 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLNddm811qouZ3kMRwZ:-MLhDi4-3zsBWzj6cjs5:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/063e656a872549514587c3336acdfd1679ea031c/hkube_python_wrapper/communication/streaming/MessageProducer.py#L35)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

> ```
>         def sendStatisticsEvery(interval):
>             while (self.active):
>                 self.sendStatistics()
>                 time.sleep(interval)
>         if (self.nodeNames):
>             runThread = Thread(name="Statistics", target=sendStatisticsEvery, args=[statisticsInterval])
>             runThread.start()
> ```
it is better to create the thread with `daemon=True`
use `from hkube_python_wrapper.util.timerImpl import Timer` as the timer implementation
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-12 11:17 UTC, yehiyam requested changes
> Reviewed 5 of 13 files at r4.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36)* status: 10 of 20 files reviewed, 20 unresolved discussions (waiting on @golanha, @NassiHarel, and @yehiyam)

___
*[hkube_python_wrapper/communication/streaming/MessageProducer.py, line 35 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLNddm811qouZ3kMRwZ:-MLhH2Iq2N6gGRVRsGM-:b92clvx) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/063e656a872549514587c3336acdfd1679ea031c/hkube_python_wrapper/communication/streaming/MessageProducer.py#L35)):*
> use from hkube_python_wrapper.util.timerImpl import Timer as the timer implementation
___
*[hkube_python_wrapper/communication/zmq/streaming/ZMQProducer.py, line 54 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLNo_dDB2IHmth312S5:-MLw6dTa6hhDpxt-ZQlg:bqz3idv) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/063e656a872549514587c3336acdfd1679ea031c/hkube_python_wrapper/communication/zmq/streaming/ZMQProducer.py#L54)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

> Since all these classes are made for the producer mechanism only,  i prefer to keep them internal.
Their logic is very specific and I don't predict the'll ever be reusable. 

</blockquote></details>

It's not a matter of reuse. Its more readable if they are in a different file
___
*[hkube_python_wrapper/wrapper/algorunner.py, line 205 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLNY1ce9cIma_5dCgwq:-MLw9wwuER90kM3anhjk:b-5k58yo) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/063e656a872549514587c3336acdfd1679ea031c/hkube_python_wrapper/wrapper/algorunner.py#L205)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

I don't I won't be able to get commands while others are running. While the algorithm is running (start) we need to be available to get a stop command.
</blockquote></details>

So what is the plan? Currently for each command you spawn a new thread
___
*[hkube_python_wrapper/wrapper/algorunner.py, line 3 at r4](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLw8bv_6hJ57x0Szu6K:-MLw8bva3x4H_1hLkpRl:b-jmfyg1) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/9e00dce0175edd6e91609bf973504f00953f4568/hkube_python_wrapper/wrapper/algorunner.py#L3)):*
> ```Python
> from __future__ import print_function, division, absolute_import
> 
> from random import randint
> ```

unsued
___
*[hkube_python_wrapper/wrapper/algorunner.py, line 47 at r4](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLw96q-AwL-XQjhT3Os:-MLw96q-AwL-XQjhT3Ot:b-jmepyd) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/9e00dce0175edd6e91609bf973504f00953f4568/hkube_python_wrapper/wrapper/algorunner.py#L47)):*
> ```Python
> 
>     @staticmethod
>     def Run(start=None, init=None, stop=None, exit=None, options=None, errorHandler=None):
> ```

unused
___
*[hkube_python_wrapper/wrapper/algorunner.py, line 157 at r4](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLw9jlc5jfRA0EB9JqV:-MLw9jlc5jfRA0EB9JqW:b99pe7r) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/9e00dce0175edd6e91609bf973504f00953f4568/hkube_python_wrapper/wrapper/algorunner.py#L157)):*
> ```
> _wrapStatless
> ```
Typo


<!-- Sent from Reviewable.io -->

2020-11-12 12:02 UTC, golanha reviewed
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36)* status: 9 of 23 files reviewed, 20 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[hkube_python_wrapper/communication/streaming/MessageProducer.py, line 35 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLNddm811qouZ3kMRwZ:-MLwHpWo24o2nRVVhe43:b-6lsy5e) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/063e656a872549514587c3336acdfd1679ea031c/hkube_python_wrapper/communication/streaming/MessageProducer.py#L35)):*
> from hkube_python_wrapper.util.timerImpl import Timer
___
*[hkube_python_wrapper/communication/zmq/streaming/ZMQProducer.py, line 54 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLNo_dDB2IHmth312S5:-MLwGdxh8G9esbyQbyuF:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/063e656a872549514587c3336acdfd1679ea031c/hkube_python_wrapper/communication/zmq/streaming/ZMQProducer.py#L54)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

It's not a matter of reuse. Its more readable if they are in a different file
</blockquote></details>

Done.
___
*[hkube_python_wrapper/config/config.py, line 49 at r2](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLN-7erERUZaQr8ukY1:-MLwBi-UEEb_poXq1NHL:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/3740a54cbc799c0f6ade60b8ba06efb80081a3e1/hkube_python_wrapper/config/config.py#L49)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
>  'bson'),
> ```
Why?
</blockquote></details>

Done.
___
*[hkube_python_wrapper/wrapper/algorunner.py, line 205 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLNY1ce9cIma_5dCgwq:-MLwKRDQCIP8lJ70NFHV:bpcg6b5) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/063e656a872549514587c3336acdfd1679ea031c/hkube_python_wrapper/wrapper/algorunner.py#L205)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

So what is the plan? Currently for each command you spawn a new thread
</blockquote></details>

threadapool?
___
*[hkube_python_wrapper/wrapper/algorunner.py, line 3 at r4](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLw8bv_6hJ57x0Szu6K:-MLwGgfb2r_C9RL64HZu:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/9e00dce0175edd6e91609bf973504f00953f4568/hkube_python_wrapper/wrapper/algorunner.py#L3)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

unsued
</blockquote></details>

Done.
___
*[hkube_python_wrapper/wrapper/algorunner.py, line 47 at r4](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLw96q-AwL-XQjhT3Os:-MLwCiYfAw8LS5UFX5eL:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/9e00dce0175edd6e91609bf973504f00953f4568/hkube_python_wrapper/wrapper/algorunner.py#L47)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

unused
</blockquote></details>

Done.
___
*[hkube_python_wrapper/wrapper/algorunner.py, line 157 at r4](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLw9jlc5jfRA0EB9JqV:-MLwCsOY37V0IoqknSQB:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/9e00dce0175edd6e91609bf973504f00953f4568/hkube_python_wrapper/wrapper/algorunner.py#L157)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

> ```
> _wrapStatless
> ```
Typo
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-12 12:07 UTC, golanha reviewed
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36)* status: 9 of 23 files reviewed, 20 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[hkube_python_wrapper/communication/streaming/MessageProducer.py, line 35 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLNddm811qouZ3kMRwZ:-MLwL9vVDxG2cxBdA22M:b1vff9s) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/063e656a872549514587c3336acdfd1679ea031c/hkube_python_wrapper/communication/streaming/MessageProducer.py#L35)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

> from hkube_python_wrapper.util.timerImpl import Timer
</blockquote></details>

I don't understand, what should I use timer for?


<!-- Sent from Reviewable.io -->

2020-11-12 13:08 UTC, yehiyam requested changes
> Reviewed 2 of 2 files at r3, 7 of 13 files at r4, 1 of 2 files at r5, 8 of 8 files at r6.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36)* status: all files reviewed, 12 unresolved discussions (waiting on @golanha, @NassiHarel, and @yehiyam)

___
*[hkube_python_wrapper/wrapper/algorunner.py, line 336 at r6](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLwYd2N1Mn5-q7O66gz:-MLwYd2O0IFkk8IVBU3E:b-dgan82) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/6b6db7e9f4541e469b9e1c5d66ead1a0ffaedfd5/hkube_python_wrapper/wrapper/algorunner.py#L336)):*
> ```
> self._storage == 'v3'
> ```
or v2?
___
*[hkube_python_wrapper/wrapper/algorunner.py, line 455 at r6](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLwZaaE6lAMMVs3MJvk:-MLwZaaF9kDsfNtLBZ-K:b-stbzas) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/6b6db7e9f4541e469b9e1c5d66ead1a0ffaedfd5/hkube_python_wrapper/wrapper/algorunner.py#L455)):*
> ```Python
> 
>     def isStreamingPipeLine(self):
>         if (self._input.get('kind') == 'stream'):
> ```

check if _input is not None


<!-- Sent from Reviewable.io -->

2020-11-12 15:20 UTC, golanha reviewed
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36)* status: 15 of 27 files reviewed, 12 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[hkube_python_wrapper/wrapper/algorunner.py, line 336 at r6](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLwYd2N1Mn5-q7O66gz:-MLwiHPnA9DdvUHXm93X:b-dcqm95) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/6b6db7e9f4541e469b9e1c5d66ead1a0ffaedfd5/hkube_python_wrapper/wrapper/algorunner.py#L336)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

> ```
> self._storage == 'v3'
> ```
or v2?
</blockquote></details>

This version of wrapper will never get v2
___
*[hkube_python_wrapper/wrapper/algorunner.py, line 455 at r6](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLwZaaE6lAMMVs3MJvk:-MLx1lhUCoNuCEVAOGMB:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/6b6db7e9f4541e469b9e1c5d66ead1a0ffaedfd5/hkube_python_wrapper/wrapper/algorunner.py#L455)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

check if _input is not None
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-12 15:36 UTC, yehiyam requested changes
> Reviewed 6 of 11 files at r8, 3 of 3 files at r9, 3 of 3 files at r10.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36)* status: all files reviewed, 11 unresolved discussions (waiting on @golanha and @NassiHarel)

___
*[hkube_python_wrapper/codeApi/hkube_api.py, line 57 at r10](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLx3aUUDEyrEvju8rEk:-MLx3aUUDEyrEvju8rEl:ba0lu4z) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/ea17b355e15772ad8e8cee0fabd3b083590fa715/hkube_python_wrapper/codeApi/hkube_api.py#L57)):*
> ```Python
>                 if (self.listeningToMessages):
>                     runThread = Thread(name="MessageListener", target=listener.start)
>                     runThread.daemon = True
> ```

You can create a class that encapsulates this in a way that is python 2.7 safe
something like hkube_python_wrapper/communication/zmq/BaseServer.py
___
*[hkube_python_wrapper/codeApi/hkube_api.py, line 87 at r10](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLx4e9RCk7a637wBLVr:-MLx4e9RCk7a637wBLVs:b34xu1a) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/ea17b355e15772ad8e8cee0fabd3b083590fa715/hkube_python_wrapper/codeApi/hkube_api.py#L87)):*
> ```Python
>             self.messageProducer.produce(msg)
> 
>     def stopStreaming(self):
> ```

Did you check that when you call `startStreaming` and `stopStreaming` repeatedly all of these threads are closed?


<!-- Sent from Reviewable.io -->

2020-11-15 11:05 UTC, yehiyam requested changes
> Reviewed 10 of 10 files at r11.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36)* status: all files reviewed, 13 unresolved discussions (waiting on @golanha and @NassiHarel)

___
*[hkube_python_wrapper/codeApi/hkube_api.py, line 83 at r11](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MMAZ0KD2Yrgfa2X6v0z:-MMAZ0KD2Yrgfa2X6v1-:b-xdramm) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/74c979dbf0021e6d9a9abfbc220f2cf0533cad05/hkube_python_wrapper/codeApi/hkube_api.py#L83)):*
> ```Python
>             for listener in self._messageListeners.values():
>                 listener.close()
>             self._messageListeners = {}
> ```

Is there a difference between `self._messageListeners = dict()` and `self._messageListeners = {}` ?
___
*[hkube_python_wrapper/util/DeamonThread.py, line 4 at r11](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MMAZXkL0l7D0xqOZIwp:-MMAZXkL0l7D0xqOZIwq:b-fxf5i5) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/74c979dbf0021e6d9a9abfbc220f2cf0533cad05/hkube_python_wrapper/util/DeamonThread.py#L4)):*
> ```Python
> 
> 
> class DeamonThread(Thread):
> ```

should be DaemonThread


<!-- Sent from Reviewable.io -->

2020-11-15 12:09 UTC, golanha reviewed
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36)* status: 21 of 30 files reviewed, 13 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[hkube_python_wrapper/codeApi/hkube_api.py, line 57 at r10](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLx3aUUDEyrEvju8rEk:-MMAUUm_-Mud6j4Rs-Oe:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/ea17b355e15772ad8e8cee0fabd3b083590fa715/hkube_python_wrapper/codeApi/hkube_api.py#L57)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

You can create a class that encapsulates this in a way that is python 2.7 safe
something like hkube_python_wrapper/communication/zmq/BaseServer.py
</blockquote></details>

Done.
___
*[hkube_python_wrapper/codeApi/hkube_api.py, line 87 at r10](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLx4e9RCk7a637wBLVr:-MMAUVVeBK1xIwVsNETi:b-60j7za) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/ea17b355e15772ad8e8cee0fabd3b083590fa715/hkube_python_wrapper/codeApi/hkube_api.py#L87)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Did you check that when you call `startStreaming` and `stopStreaming` repeatedly all of these threads are closed?
</blockquote></details>

I have now
___
*[hkube_python_wrapper/codeApi/hkube_api.py, line 83 at r11](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MMAZ0KD2Yrgfa2X6v0z:-MMAl-SU8MW2zMDH25gn:b56dirf) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/74c979dbf0021e6d9a9abfbc220f2cf0533cad05/hkube_python_wrapper/codeApi/hkube_api.py#L83)):*
> self._messageListeners = {}
No I'll put dict() if its clearer...
___
*[hkube_python_wrapper/util/DeamonThread.py, line 4 at r11](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MMAZXkL0l7D0xqOZIwp:-MMAnm8DD8Agdgeo4Wc4:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/74c979dbf0021e6d9a9abfbc220f2cf0533cad05/hkube_python_wrapper/util/DeamonThread.py#L4)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

should be DaemonThread
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-15 13:16 UTC, yehiyam approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 9 of 9 files at r12.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-:-MMB2CU-5U24AHcRck9w:bnfp4nl)* status: all files reviewed, 10 unresolved discussions (waiting on @golanha and @NassiHarel)

___
*[hkube_python_wrapper/wrapper/algorunner.py, line 44 at r12](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MMB1C8d5NRU8TWmPvE6:-MMB1C8d5NRU8TWmPvE7:b2qza7o) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/48ddffc718e402948075daf3e849ecb8e368935b/hkube_python_wrapper/wrapper/algorunner.py#L44)):*
> ```
> WorkdrListener
> ```
Typo


<!-- Sent from Reviewable.io -->

2020-11-15 13:26 UTC, NassiHarel requested changes
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36)* status: all files reviewed, 12 unresolved discussions (waiting on @golanha and @NassiHarel)

___
*[hkube_python_wrapper/wrapper/algorunner.py, line 303 at r2](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MLN-ydG-IpATL8cx3XV:-MMB3rw47jx6Ucz5x73K:b-tl7ky3) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/3740a54cbc799c0f6ade60b8ba06efb80081a3e1/hkube_python_wrapper/wrapper/algorunner.py#L303)):*
> ```
>                 self._handle_response(algorithmData, jobId,
>                                       taskId, nodeName, savePaths, span)
> ```
The problem is not the if-else, this format makes the function spread on two lines,
___
*[hkube_python_wrapper/wrapper/algorunner.py, line 329 at r12](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MMB48bv89_cq5AOS4it:-MMB48bv89_cq5AOS4iu:bdsg9s7) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/48ddffc718e402948075daf3e849ecb8e368935b/hkube_python_wrapper/wrapper/algorunner.py#L329)):*
> ```
>                 self._handle_response(algorithmData, jobId,
>                                       taskId, nodeName, savePaths, span)
> ```
The problem with this format is that function spread on two lines
___
*[hkube_python_wrapper/wrapper/algorunner.py, line 340 at r12](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MMB4OxXCguptwUmGUoF:-MMB4OxXCguptwUmGUoG:bkvapj) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/48ddffc718e402948075daf3e849ecb8e368935b/hkube_python_wrapper/wrapper/algorunner.py#L340)):*
> ```
>             self._handle_responseV2_V3(
>                 algorithmData, jobId, taskId, nodeName, savePaths, span)
> ```
The problem with this format is that function spread on two lines


<!-- Sent from Reviewable.io -->

2020-11-15 14:02 UTC, golanha reviewed
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36)* status: 29 of 30 files reviewed, 4 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[hkube_python_wrapper/wrapper/algorunner.py, line 44 at r12](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MMB1C8d5NRU8TWmPvE6:-MMBAw_16-fJ8vISFM0M:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/48ddffc718e402948075daf3e849ecb8e368935b/hkube_python_wrapper/wrapper/algorunner.py#L44)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

> ```
> WorkdrListener
> ```
Typo
</blockquote></details>

Done.
___
*[hkube_python_wrapper/wrapper/algorunner.py, line 329 at r12](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MMB48bv89_cq5AOS4it:-MMBC21i7rtfvmZbYcbg:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/48ddffc718e402948075daf3e849ecb8e368935b/hkube_python_wrapper/wrapper/algorunner.py#L329)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
>                 self._handle_response(algorithmData, jobId,
>                                       taskId, nodeName, savePaths, span)
> ```
The problem with this format is that function spread on two lines
</blockquote></details>

Done.
___
*[hkube_python_wrapper/wrapper/algorunner.py, line 340 at r12](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36#-MMB4OxXCguptwUmGUoF:-MMBCOax3q09hqJ1fX07:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/48ddffc718e402948075daf3e849ecb8e368935b/hkube_python_wrapper/wrapper/algorunner.py#L340)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
>             self._handle_responseV2_V3(
>                 algorithmData, jobId, taskId, nodeName, savePaths, span)
> ```
The problem with this format is that function spread on two lines
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-15 14:39 UTC, yehiyam approved these changes
> Reviewed 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/36)* status: all files reviewed, 3 unresolved discussions (waiting on @NassiHarel)



<!-- Sent from Reviewable.io -->

2020-11-15 14:39 UTC, merged