Streaming subpipe
kube-HPC/python-wrapper.hkube pull request #38
Opened 2020-11-18 14:19 UTC by golanha

2020-11-24 09:56 UTC, NassiHarel requested changes
> Reviewed 2 of 15 files at r7.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38)* status: 2 of 13 files reviewed, 4 unresolved discussions (waiting on @golanha and @NassiHarel)

___
*[hkube_python_wrapper/codeApi/hkube_api.py, line 48 at r7](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MMtXu0uDo8ElniCbdXj:-MMtXu0uDo8ElniCbdXk:b-2o1gke) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/ff6745190431dca8711e8d577e14bc756137b617/hkube_python_wrapper/codeApi/hkube_api.py#L48)):*
> ```
>             remoteAddress = 'tcp://' + \
>                             predecessor['address']['host'] + ':' + \
>                             str(predecessor['address']['port'])
> ```

Maybe use format:
```
    host = predecessor['address']['host']
    port = str(predecessor['address']['port'])
    remoteAddress = 'tcp://{host}:{port}'.format(host=host, port=port)
```
___
*[hkube_python_wrapper/communication/streaming/MessageProducer.py, line 69 at r7](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MMtfE-f8ibS7XgiJyq-:-MMtfE-f8ibS7XgiJyq0:b-v9amqj) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/ff6745190431dca8711e8d577e14bc756137b617/hkube_python_wrapper/communication/streaming/MessageProducer.py#L69)):*
> ```
> queueSize = self.adapter.queueSize(node["nodeName"])
> ```
We will get back to old `childs`
___
*[hkube_python_wrapper/communication/zmq/streaming/producer/MessageQueue.py, line 17 at r7](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MMtcszSB7FcNft3A5Eq:-MMtcszSB7FcNft3A5Er:b-ieeopf) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/ff6745190431dca8711e8d577e14bc756137b617/hkube_python_wrapper/communication/zmq/streaming/producer/MessageQueue.py#L17)):*
> ```
> self.queue = []
> ```
I think that you need a queue per consumer, searching each tick in the queue is inefficient.
(Even if you have `indexPerConsumer`)

Something like:
```
 self.queue = {
            type,
            queue: []
        }
  self.queueSize = 0
```
___
*[hkube_python_wrapper/communication/zmq/streaming/producer/ZMQProducer.py, line 56 at r7](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MMtcPM0-NIfIQo0dzkr:-MMtcPM0-NIfIQo0dzks:b-b5nt56) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/ff6745190431dca8711e8d577e14bc756137b617/hkube_python_wrapper/communication/zmq/streaming/producer/ZMQProducer.py#L56)):*
> ```
> if socks.get(self._backend) == zmq.POLLIN:
> ```

UnboundLocalError: local variable 'socks' referenced before assignment


<!-- Sent from Reviewable.io -->

2020-11-24 10:03 UTC, NassiHarel requested changes
> Reviewed 3 of 15 files at r7.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38)* status: 5 of 13 files reviewed, 7 unresolved discussions (waiting on @golanha)

___
*[hkube_python_wrapper/codeApi/hkube_api.py, line 86 at r8](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MMtfwsF3phlxMK1YRRT:-MMtfwsG2lrHWudgALGZ:b-oqqzi4) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/277521809f0a23bd885c04b55a094376e03c4d18/hkube_python_wrapper/codeApi/hkube_api.py#L86)):*
> ```
> raise Exception("Default flow is None")
> ```
But what if there are no "next nodes"?
___
*[hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, line 68 at r8](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MMtgcw8CKfpv_7LK8Xs:-MMtgcw9Dueu6__UUmsm:b-wik22y) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/277521809f0a23bd885c04b55a094376e03c4d18/hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py#L68)):*
> ```
>  msgpack
> ```
???
___
*[hkube_python_wrapper/communication/zmq/streaming/producer/ZMQProducer.py, line 24 at r8](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MMth9mE7i-qCpc-m-Np:-MMth9mE7i-qCpc-m-Nq:bmupsl1) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/277521809f0a23bd885c04b55a094376e03c4d18/hkube_python_wrapper/communication/zmq/streaming/producer/ZMQProducer.py#L24)):*
> ```
> self.me = me
> ```
Who?

This is `nodeName`?


<!-- Sent from Reviewable.io -->

2020-11-24 13:32 UTC, golanha reviewed
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38)* status: 5 of 13 files reviewed, 8 unresolved discussions (waiting on @NassiHarel)

___
*[hkube_python_wrapper/codeApi/hkube_api.py, line 48 at r7](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MMtXu0uDo8ElniCbdXj:-MMuG1Qz5hKspVVjQPIV:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/ff6745190431dca8711e8d577e14bc756137b617/hkube_python_wrapper/codeApi/hkube_api.py#L48)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
>             remoteAddress = 'tcp://' + \
>                             predecessor['address']['host'] + ':' + \
>                             str(predecessor['address']['port'])
> ```

Maybe use format:
```
    host = predecessor['address']['host']
    port = str(predecessor['address']['port'])
    remoteAddress = 'tcp://{host}:{port}'.format(host=host, port=port)
```
</blockquote></details>

Done.
___
*[hkube_python_wrapper/codeApi/hkube_api.py, line 48 at r8](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MMuEjkM96Zox1WTp7Vq:-MMuEjkM96Zox1WTp7Vr:b7egrmo) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/277521809f0a23bd885c04b55a094376e03c4d18/hkube_python_wrapper/codeApi/hkube_api.py#L48)):*
> ```
> remoteAddress = 'tcp://' + \
> ```
___
*[hkube_python_wrapper/codeApi/hkube_api.py, line 86 at r8](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MMtfwsF3phlxMK1YRRT:-MMuGIPPAshw1eLxdiH3:b-sr1hhy) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/277521809f0a23bd885c04b55a094376e03c4d18/hkube_python_wrapper/codeApi/hkube_api.py#L86)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> raise Exception("Default flow is None")
> ```
But what if there are no "next nodes"?
</blockquote></details>

Still there should always be a default flow, from which I can learn there is not next node.
___
*[hkube_python_wrapper/communication/streaming/MessageProducer.py, line 69 at r7](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MMtfE-f8ibS7XgiJyq-:-MMuGbIz2gKJf9Rqi9pq:bczdhz6) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/ff6745190431dca8711e8d577e14bc756137b617/hkube_python_wrapper/communication/streaming/MessageProducer.py#L69)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> queueSize = self.adapter.queueSize(node["nodeName"])
> ```
We will get back to old `childs`
</blockquote></details>

I'll adjust when you make the change 
___
*[hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, line 68 at r8](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MMtgcw8CKfpv_7LK8Xs:-MMuGks-4DPCPAc6mIJb:b-lrdfwg) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/277521809f0a23bd885c04b55a094376e03c4d18/hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py#L68)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
>  msgpack
> ```
???
</blockquote></details>

I need encoding for the communication, I chose msgpack. I see no reason to have it configurable.
___
*[hkube_python_wrapper/communication/zmq/streaming/producer/MessageQueue.py, line 17 at r7](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MMtcszSB7FcNft3A5Eq:-MMuHI4s0O34oA1mZZbs:bjt1np2) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/ff6745190431dca8711e8d577e14bc756137b617/hkube_python_wrapper/communication/zmq/streaming/producer/MessageQueue.py#L17)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> self.queue = []
> ```
I think that you need a queue per consumer, searching each tick in the queue is inefficient.
(Even if you have `indexPerConsumer`)

Something like:
```
 self.queue = {
            type,
            queue: []
        }
  self.queueSize = 0
```
</blockquote></details>

I remember we spoke about it. But when I wanted to make the change I found out I have a problem losing messages when the queue size gets too large.
this way I can lose a message an know no other queue is still holding it. 
___
*[hkube_python_wrapper/communication/zmq/streaming/producer/ZMQProducer.py, line 56 at r7](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MMtcPM0-NIfIQo0dzkr:-MMuI6Mx6Shfe9-Onnqu:befedfg) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/ff6745190431dca8711e8d577e14bc756137b617/hkube_python_wrapper/communication/zmq/streaming/producer/ZMQProducer.py#L56)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> if socks.get(self._backend) == zmq.POLLIN:
> ```

UnboundLocalError: local variable 'socks' referenced before assignment
</blockquote></details>

I break on failure now
___
*[hkube_python_wrapper/communication/zmq/streaming/producer/ZMQProducer.py, line 24 at r8](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MMth9mE7i-qCpc-m-Np:-MMuHpYuBxf_OaFX9g6C:bqbhana) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/277521809f0a23bd885c04b55a094376e03c4d18/hkube_python_wrapper/communication/zmq/streaming/producer/ZMQProducer.py#L24)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> self.me = me
> ```
Who?

This is `nodeName`?
</blockquote></details>

I don't use the term nodeName at this level of communication. Me means the my id what ever I represent. 


<!-- Sent from Reviewable.io -->

2020-11-24 14:17 UTC, NassiHarel requested changes
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38)* status: 5 of 13 files reviewed, 8 unresolved discussions (waiting on @golanha and @NassiHarel)

___
*[hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, line 68 at r8](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MMtgcw8CKfpv_7LK8Xs:-MMuaOw46eTXeMwpbwY_:b4t9cgk) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/277521809f0a23bd885c04b55a094376e03c4d18/hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py#L68)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

I need encoding for the communication, I chose msgpack. I see no reason to have it configurable.
</blockquote></details>

But why not using the `encoding` module?
___
*[hkube_python_wrapper/communication/zmq/streaming/producer/ZMQProducer.py, line 56 at r7](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MMtcPM0-NIfIQo0dzkr:-MMub7oH683qXFgG6z4s:bene2wl) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/ff6745190431dca8711e8d577e14bc756137b617/hkube_python_wrapper/communication/zmq/streaming/producer/ZMQProducer.py#L56)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

I break on failure now
</blockquote></details>

WHAT?
But the exception is above..... and still happens....
UnboundLocalError: local variable 'socks' referenced before assignment


<!-- Sent from Reviewable.io -->

2020-11-24 14:53 UTC, NassiHarel requested changes
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38)* status: 5 of 13 files reviewed, 9 unresolved discussions (waiting on @golanha and @NassiHarel)

___
*[hkube_python_wrapper/wrapper/statelessAlgoWrapper.py, line 27 at r9](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MMujX8YCEEU2hKU7tg7:-MMujX8ZCp_UyLIa7OUh:b-ed2pb7) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/990a3fcbc4f200913403581a98047d47a95d99bc/hkube_python_wrapper/wrapper/statelessAlgoWrapper.py#L27)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>         if (foundInInput):
>             options['input'] = input
>         else:
>             options['input'] = [msg]
>         try:
> ```
</details>

That way I will loose my original input...


<!-- Sent from Reviewable.io -->

2020-11-24 14:54 UTC, NassiHarel requested changes
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38)* status: 5 of 13 files reviewed, 9 unresolved discussions (waiting on @golanha and @NassiHarel)

___
*[hkube_python_wrapper/wrapper/statelessAlgoWrapper.py, line 30 at r9](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MMujiLKCzEn9WuzkqUb:-MMujiLKCzEn9WuzkqUc:b-ifdv4e) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/990a3fcbc4f200913403581a98047d47a95d99bc/hkube_python_wrapper/wrapper/statelessAlgoWrapper.py#L30)):*
> ```
>  options['input'] = [msg]
> ```

That way I will lose my original input...


<!-- Sent from Reviewable.io -->

2020-11-24 15:51 UTC, NassiHarel requested changes
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38)* status: 5 of 13 files reviewed, 8 unresolved discussions (waiting on @golanha, @NassiHarel, and @yehiyam)

___
*[hkube_python_wrapper/codeApi/hkube_api.py, line 86 at r8](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MMtfwsF3phlxMK1YRRT:-MMusVNr9tddoNlHhb9e:b-8833ez) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/277521809f0a23bd885c04b55a094376e03c4d18/hkube_python_wrapper/codeApi/hkube_api.py#L86)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

Still there should always be a default flow, from which I can learn there is not next node.
</blockquote></details>

I think that you need to check first if:
1. there is `messageProducer`
then
2. there are `messageProducer.nodes`
then
3. there is `flow`
___
*[hkube_python_wrapper/communication/streaming/MessageProducer.py, line 69 at r7](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MMtfE-f8ibS7XgiJyq-:-MMuuyuzDvCi2Naqlx8D:b-mej5mo) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/ff6745190431dca8711e8d577e14bc756137b617/hkube_python_wrapper/communication/streaming/MessageProducer.py#L69)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

I'll adjust when you make the change 
</blockquote></details>

Now you can


<!-- Sent from Reviewable.io -->

2020-11-24 16:15 UTC, NassiHarel requested changes
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38)* status: 5 of 13 files reviewed, 9 unresolved discussions (waiting on @golanha, @NassiHarel, and @yehiyam)

___
*[hkube_python_wrapper/wrapper/algorunner.py, line 271 at r9](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MMv1TmdBfIwuK3xAlOz:-MMv1TmdBfIwuK3xAlP-:b-1vjxdp) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/990a3fcbc4f200913403581a98047d47a95d99bc/hkube_python_wrapper/wrapper/algorunner.py#L271)):*
> ```
> if self.isStreamingPipeLine() and options.get('stateType') == 'stateless':
> ```
change to != stateful


<!-- Sent from Reviewable.io -->

2020-11-25 11:06 UTC, golanha reviewed
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38)* status: 4 of 13 files reviewed, 9 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[hkube_python_wrapper/codeApi/hkube_api.py, line 86 at r8](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MMtfwsF3phlxMK1YRRT:-MMyAGC-0KdXzh6bxMT6:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/277521809f0a23bd885c04b55a094376e03c4d18/hkube_python_wrapper/codeApi/hkube_api.py#L86)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

I think that you need to check first if:
1. there is `messageProducer`
then
2. there are `messageProducer.nodes`
then
3. there is `flow`

</blockquote></details>

Done.
___
*[hkube_python_wrapper/communication/streaming/MessageProducer.py, line 69 at r7](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MMtfE-f8ibS7XgiJyq-:-MMyc7UtC6INp1JclHpi:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/ff6745190431dca8711e8d577e14bc756137b617/hkube_python_wrapper/communication/streaming/MessageProducer.py#L69)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

Now you can
</blockquote></details>

Done.
___
*[hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, line 68 at r8](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MMtgcw8CKfpv_7LK8Xs:-MMy0_L_0Y-r-ZhCp_He:bofo1c4) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/277521809f0a23bd885c04b55a094376e03c4d18/hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py#L68)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

But why not using the `encoding` module?
</blockquote></details>

This way I don't have to make the zmq communication layer depended on encoding module. Code is less spaghetti, you could take the zmq classes and use them elsewhere. 
___
*[hkube_python_wrapper/communication/zmq/streaming/producer/ZMQProducer.py, line 56 at r7](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MMtcPM0-NIfIQo0dzkr:-MMy281yAfSsOU3tCcsn:bvg26l6) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/ff6745190431dca8711e8d577e14bc756137b617/hkube_python_wrapper/communication/zmq/streaming/producer/ZMQProducer.py#L56)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

WHAT?
But the exception is above..... and still happens....
UnboundLocalError: local variable 'socks' referenced before assignment
</blockquote></details>

Your are right, I put it in the wrong place. Actually there are other places to break if exception occurred while no longer active, I am adding them. 
___
*[hkube_python_wrapper/wrapper/algorunner.py, line 271 at r9](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MMv1TmdBfIwuK3xAlOz:-MMy6JwT-uZu55SSmB4V:b-8h1wub) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/990a3fcbc4f200913403581a98047d47a95d99bc/hkube_python_wrapper/wrapper/algorunner.py#L271)):*
> if self.isStreamingPipeLine() and options.get('stateType') == 'stateless'
As we spoke, I leave it as is
___
*[hkube_python_wrapper/wrapper/statelessAlgoWrapper.py, line 30 at r9](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MMujiLKCzEn9WuzkqUb:-MMy8Inf4R5vBZ3I2C52:bcvrg5u) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/990a3fcbc4f200913403581a98047d47a95d99bc/hkube_python_wrapper/wrapper/statelessAlgoWrapper.py#L30)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
>  options['input'] = [msg]
> ```

That way I will lose my original input...
</blockquote></details>

Adding the message separately  


<!-- Sent from Reviewable.io -->

2020-11-25 13:46 UTC, NassiHarel requested changes
> Reviewed 1 of 15 files at r7, 1 of 4 files at r8, 6 of 6 files at r10.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38)* status: 12 of 13 files reviewed, 7 unresolved discussions (waiting on @golanha, @NassiHarel, and @yehiyam)

___
*[hkube_python_wrapper/communication/streaming/MessageListener.py, line 2 at r10](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MMzKM0L81Z09SuMMzaA:-MMzKM0MCTfOKhgE-pas:b-38x9zv) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/96a899112654d95ac22bdbefd1973ebbc2157bdc/hkube_python_wrapper/communication/streaming/MessageListener.py#L2)):*
> ```Python
> from hkube_python_wrapper.communication.zmq.streaming.ZMQListener import ZMQListener
> import time
> ```

re-arrange imports
___
*[hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, line 68 at r8](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MMtgcw8CKfpv_7LK8Xs:-MMzICqSA1sThGfFkZXD:b7bwtgw) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/277521809f0a23bd885c04b55a094376e03c4d18/hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py#L68)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

This way I don't have to make the zmq communication layer depended on encoding module. Code is less spaghetti, you could take the zmq classes and use them elsewhere. 
</blockquote></details>

But you have the `Flow` object inside `ZMQProducer`, this is not coupling?
You don't have to depend on the encoding module, for that reason there is something called "dependency injection"
___
*[hkube_python_wrapper/communication/zmq/streaming/producer/MessageQueue.py, line 17 at r7](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MMtcszSB7FcNft3A5Eq:-MMzcwzzE9POT1NZvElI:b9azi5t) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/ff6745190431dca8711e8d577e14bc756137b617/hkube_python_wrapper/communication/zmq/streaming/producer/MessageQueue.py#L17)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

I remember we spoke about it. But when I wanted to make the change I found out I have a problem losing messages when the queue size gets too large.
this way I can lose a message an know no other queue is still holding it. 
</blockquote></details>

I ran a little experiment:
A >> C -- send 1 msg per sec, with a delay of 5 sec.
A  >> B -- send 40 msg per sec, with a delay of 0.1 sec.

Node C finds the msg in the queue about 0.005 ms.
Node B finds the msg in the queue about 10.5 ms.
___
*[hkube_python_wrapper/communication/zmq/streaming/producer/ZMQProducer.py, line 38 at r10](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MMzRjm-4hnN01l77J8e:-MMzRjm-4hnN01l77J8f:bekjhlo) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/96a899112654d95ac22bdbefd1973ebbc2157bdc/hkube_python_wrapper/communication/zmq/streaming/producer/ZMQProducer.py#L38)):*
> ```
> print('Loosing a message, queue filled up ')
> ```
This will blow the stdout....
___
*[hkube_python_wrapper/communication/zmq/streaming/producer/ZMQProducer.py, line 95 at r10](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MMzYHf4EztzwK4TBQFM:-MMzYHf4EztzwK4TBQFN:b-j2uv1) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/96a899112654d95ac22bdbefd1973ebbc2157bdc/hkube_python_wrapper/communication/zmq/streaming/producer/ZMQProducer.py#L95)):*
> ```
>  nextItemIndex = self.messageQueue.nextMessageIndex(type)
> ```
You are calling this function rapidly and then check if the `workerQueu` is not none.
This does extra work to find a message if the workerQueu is none.
The logic should be the opposite...


<!-- Sent from Reviewable.io -->

2020-11-26 08:20 UTC, golanha reviewed
> Reviewed 1 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38)* status: 11 of 13 files reviewed, 7 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[hkube_python_wrapper/communication/streaming/MessageListener.py, line 2 at r10](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MMzKM0L81Z09SuMMzaA:-MN2Yfxe8BAa-75R5Yy2:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/96a899112654d95ac22bdbefd1973ebbc2157bdc/hkube_python_wrapper/communication/streaming/MessageListener.py#L2)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

re-arrange imports
</blockquote></details>

Done.
___
*[hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, line 68 at r8](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MMtgcw8CKfpv_7LK8Xs:-MN2Tk00Dy1OF_tMI7-C:b3w05ks) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/277521809f0a23bd885c04b55a094376e03c4d18/hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py#L68)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

But you have the `Flow` object inside `ZMQProducer`, this is not coupling?
You don't have to depend on the encoding module, for that reason there is something called "dependency injection"
</blockquote></details>

In java its clearer because I made real independent modules. 
Its true Flow will have to be part of a common module and considered part of the solution ZMQ layer provides . 
But I can easily avoid having zmq depend on encoding.
 
___
*[hkube_python_wrapper/communication/zmq/streaming/producer/MessageQueue.py, line 17 at r7](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MMtcszSB7FcNft3A5Eq:-MN2XR9B2xxgaWios1p9:b3z8x91) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/ff6745190431dca8711e8d577e14bc756137b617/hkube_python_wrapper/communication/zmq/streaming/producer/MessageQueue.py#L17)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

I ran a little experiment:
A >> C -- send 1 msg per sec, with a delay of 5 sec.
A  >> B -- send 40 msg per sec, with a delay of 0.1 sec.

Node C finds the msg in the queue about 0.005 ms.
Node B finds the msg in the queue about 10.5 ms.

</blockquote></details>

I still prefer to leave it as is
___
*[hkube_python_wrapper/communication/zmq/streaming/producer/ZMQProducer.py, line 56 at r7](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MMtcPM0-NIfIQo0dzkr:-MN2baMU7SXldCvRyaBW:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/ff6745190431dca8711e8d577e14bc756137b617/hkube_python_wrapper/communication/zmq/streaming/producer/ZMQProducer.py#L56)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

Your are right, I put it in the wrong place. Actually there are other places to break if exception occurred while no longer active, I am adding them. 
</blockquote></details>

Done.
___
*[hkube_python_wrapper/communication/zmq/streaming/producer/ZMQProducer.py, line 38 at r10](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MMzRjm-4hnN01l77J8e:-MN2ZDhR56GRTrjiFHe_:bh42i0m) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/96a899112654d95ac22bdbefd1973ebbc2157bdc/hkube_python_wrapper/communication/zmq/streaming/producer/ZMQProducer.py#L38)):*
> print('Loosing a message, queue filled up ')
I'll remove the message. You can see lost messages as part of the statistics
___
*[hkube_python_wrapper/communication/zmq/streaming/producer/ZMQProducer.py, line 95 at r10](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MMzYHf4EztzwK4TBQFM:-MN2YKplD7ObXoLQFq1l:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/96a899112654d95ac22bdbefd1973ebbc2157bdc/hkube_python_wrapper/communication/zmq/streaming/producer/ZMQProducer.py#L95)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
>  nextItemIndex = self.messageQueue.nextMessageIndex(type)
> ```
You are calling this function rapidly and then check if the `workerQueu` is not none.
This does extra work to find a message if the workerQueu is none.
The logic should be the opposite...

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-26 08:25 UTC, golanha reviewed
> Reviewed 2 of 2 files at r11.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38)* status: all files reviewed, 7 unresolved discussions (waiting on @NassiHarel and @yehiyam)



<!-- Sent from Reviewable.io -->

2020-11-26 08:49 UTC, NassiHarel requested changes
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38)* status: all files reviewed, 3 unresolved discussions (waiting on @golanha and @yehiyam)

___
*[hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, line 68 at r8](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MMtgcw8CKfpv_7LK8Xs:-MN2gVNd8E5YtvJptznN:binodby) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/277521809f0a23bd885c04b55a094376e03c4d18/hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py#L68)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

In java its clearer because I made real independent modules. 
Its true Flow will have to be part of a common module and considered part of the solution ZMQ layer provides . 
But I can easily avoid having zmq depend on encoding.
 
</blockquote></details>

But you still have a dependency on `msgpack`, and what if I want different encoding?
anyway, this is not a "generic zmq streaming layer", this is not PyPI package.
If you do a dependency injection like this, it will be less coupled.

```
class ZMQListener(object):
    def __init__(self, remoteAddress, onMessage, consumerType, `encoding`):
        self._encoding = `encoding`

```
I prefer that any action will be in only one single place.
___
*[hkube_python_wrapper/communication/zmq/streaming/producer/MessageQueue.py, line 17 at r7](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MMtcszSB7FcNft3A5Eq:-MN2j9nW86lkq047s39P:b-ssv6kh) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/ff6745190431dca8711e8d577e14bc756137b617/hkube_python_wrapper/communication/zmq/streaming/producer/MessageQueue.py#L17)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

I still prefer to leave it as is
</blockquote></details>

If you prefer O(n) instead of O(1), fine.


<!-- Sent from Reviewable.io -->

2020-11-26 12:34 UTC, golanha reviewed
> Reviewed 4 of 4 files at r12.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38)* status: all files reviewed, 3 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, line 68 at r8](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MMtgcw8CKfpv_7LK8Xs:-MN3XsD5EcT5XfcTBTc2:b32wtd) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/277521809f0a23bd885c04b55a094376e03c4d18/hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py#L68)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

But you still have a dependency on `msgpack`, and what if I want different encoding?
anyway, this is not a "generic zmq streaming layer", this is not PyPI package.
If you do a dependency injection like this, it will be less coupled.

```
class ZMQListener(object):
    def __init__(self, remoteAddress, onMessage, consumerType, `encoding`):
        self._encoding = `encoding`

```
I prefer that any action will be in only one single place.

</blockquote></details>

ok
___
*[hkube_python_wrapper/communication/zmq/streaming/producer/MessageQueue.py, line 17 at r7](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MMtcszSB7FcNft3A5Eq:-MN2q_qb2ybMQ4BlRaWY:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/ff6745190431dca8711e8d577e14bc756137b617/hkube_python_wrapper/communication/zmq/streaming/producer/MessageQueue.py#L17)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

If you prefer O(n) instead of O(1), fine.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-01 15:45 UTC, yehiyam requested changes
> Reviewed 3 of 20 files at r1, 3 of 3 files at r13.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38)* status: all files reviewed, 10 unresolved discussions (waiting on @golanha and @NassiHarel)

___
*[hkube_python_wrapper/codeApi/hkube_api.py, line 31 at r13](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MNTwUYBArHIVd0vI0Mw:-MNTwUYBArHIVd0vI0Mx:b-2dayu1) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/f01439eb0e861dff985b92b9b26b4f35b8811820/hkube_python_wrapper/codeApi/hkube_api.py#L31)):*
> ```Python
>         self.defaultFlow = None
> 
>     def setParsedFlows(self, flows, defaultFlow):
> ```

HKubeApi should only contain methods that the user is expected to call. Why are all of the streaming methods here? especially all of the set* methods
___
*[hkube_python_wrapper/codeApi/hkube_api.py, line 36 at r13](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MNTx8P35xGBdjZRYTas:-MNTx8P4AMt0iOHbmKil:b-qgoc99) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/f01439eb0e861dff985b92b9b26b4f35b8811820/hkube_python_wrapper/codeApi/hkube_api.py#L36)):*
> ```Python
> 
>     def setupStreamingProducer(self, onStatistics, producerConfig, nextNodes, me):
>         self.messageProducer = MessageProducer(producerConfig, nextNodes, me)
> ```

Why is the producer created even if it is not started (nextNodes==None)
___
*[hkube_python_wrapper/codeApi/hkube_api.py, line 82 at r13](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MNTwF6EBsvWwrF8CW1L:-MNTwF6EBsvWwrF8CW1M:bls23p6) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/f01439eb0e861dff985b92b9b26b4f35b8811820/hkube_python_wrapper/codeApi/hkube_api.py#L82)):*
> ```Python
>                 listener.start()
> 
>     def sendMessage(self, msg, flowName=None):
> ```

Is this parameter used anywhere? I couldn't find it
___
*[hkube_python_wrapper/communication/streaming/MessageListener.py, line 23 at r13](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MNTbaqB481zUK5VdyXi:-MNTbaqB481zUK5VdyXj:b-9ghbje) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/f01439eb0e861dff985b92b9b26b4f35b8811820/hkube_python_wrapper/communication/streaming/MessageListener.py#L23)):*
> ```Python
>         self.messageListeners.append(listener)
> 
>     def onMessage(self, envelope, header, msg):
> ```

`envelop` is used in many places in the code. Isn't this zmq specific term/structure?
___
*[hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, line 50 at r13](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MNTamgp5riV3WSyCQrq:-MNTamgp5riV3WSyCQrr:b-3togjm) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/f01439eb0e861dff985b92b9b26b4f35b8811820/hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py#L50)):*
> ```Python
>                     print(e)
>                     raise e
>                 break
> ```

what will happen when you `break`?
___
*[hkube_python_wrapper/wrapper/algorunner.py, line 331 at r13](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MNTt06v-wcXg3VS_Az7:-MNTt06v-wcXg3VS_Az8:bvbv4l7) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/f01439eb0e861dff985b92b9b26b4f35b8811820/hkube_python_wrapper/wrapper/algorunner.py#L331)):*
> ```Python
>             if not (self.stopped):
>                 self._handle_response(algorithmData, jobId, taskId, nodeName, savePaths, span)
>             self.runningStartThread = None
> ```

you're not clearing this variable in case of Exception
___
*[hkube_python_wrapper/wrapper/statelessAlgoWrapper.py, line 20 at r13](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MNTxWu02BYTcR2C0UzG:-MNTxWu02BYTcR2C0UzH:b-hrx7xy) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/f01439eb0e861dff985b92b9b26b4f35b8811820/hkube_python_wrapper/wrapper/statelessAlgoWrapper.py#L20)):*
> ```Python
>         options['streamInput'] = {'message': msg, 'origin': origin}
>         try:
>             result = self.originalAlgorithm['start'](options, self._hkubeApi)
> ```

The user has no way of sending to another flow
___
*[hkube_python_wrapper/wrapper/statelessAlgoWrapper.py, line 47 at r13](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MNTyKMh-ZoVoW8KKoQ3:-MNTyKMh-ZoVoW8KKoQ4:bg6gr31) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/f01439eb0e861dff985b92b9b26b4f35b8811820/hkube_python_wrapper/wrapper/statelessAlgoWrapper.py#L47)):*
> ```
> if not (self.originalAlgorithm.get('stop') is None):
> ```
`if self.originalAlgorithm.get('stop')` is much shorter


<!-- Sent from Reviewable.io -->

2020-12-02 14:49 UTC, golanha reviewed
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38)* status: 3 of 15 files reviewed, 10 unresolved discussions (waiting on @golanha, @NassiHarel, and @yehiyam)

___
*[hkube_python_wrapper/codeApi/hkube_api.py, line 31 at r13](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MNTwUYBArHIVd0vI0Mw:-MNYSFLdBL2wpwRAYeon:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/f01439eb0e861dff985b92b9b26b4f35b8811820/hkube_python_wrapper/codeApi/hkube_api.py#L31)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

HKubeApi should only contain methods that the user is expected to call. Why are all of the streaming methods here? especially all of the set* methods
</blockquote></details>

Done.
___
*[hkube_python_wrapper/codeApi/hkube_api.py, line 36 at r13](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MNTx8P35xGBdjZRYTas:-MNXE5uXBMV4h3P0Q6Tq:b-dpo6x) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/f01439eb0e861dff985b92b9b26b4f35b8811820/hkube_python_wrapper/codeApi/hkube_api.py#L36)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Why is the producer created even if it is not started (nextNodes==None)
</blockquote></details>

Now algorunner._setupStreamingProducer won't be called if _input[childs] is empty
___
*[hkube_python_wrapper/codeApi/hkube_api.py, line 82 at r13](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MNTwF6EBsvWwrF8CW1L:-MNYvNYj5oXkAuH8jov-:b-dd63fq) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/f01439eb0e861dff985b92b9b26b4f35b8811820/hkube_python_wrapper/codeApi/hkube_api.py#L82)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Is this parameter used anywhere? I couldn't find it
</blockquote></details>

Used in tests now
___
*[hkube_python_wrapper/communication/streaming/MessageListener.py, line 23 at r13](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MNTbaqB481zUK5VdyXi:-MNYSHcy589CdVo7guoD:b7agbxr) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/f01439eb0e861dff985b92b9b26b4f35b8811820/hkube_python_wrapper/communication/streaming/MessageListener.py#L23)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

`envelop` is used in many places in the code. Isn't this zmq specific term/structure?
</blockquote></details>

changed to messageFlowPattern
___
*[hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, line 50 at r13](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MNTamgp5riV3WSyCQrq:-MNXCQrM1kLQNKJ6qZCY:bld4hzs) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/f01439eb0e861dff985b92b9b26b4f35b8811820/hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py#L50)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

what will happen when you `break`?
</blockquote></details>

I break when self.active is false, meaning I was suppose to break from the loop next time I reach the while (self.active)
___
*[hkube_python_wrapper/wrapper/algorunner.py, line 331 at r13](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MNTt06v-wcXg3VS_Az7:-MNXEzJG5eULDUxTOuoA:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/f01439eb0e861dff985b92b9b26b4f35b8811820/hkube_python_wrapper/wrapper/algorunner.py#L331)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

you're not clearing this variable in case of Exception
</blockquote></details>

Done.
___
*[hkube_python_wrapper/wrapper/statelessAlgoWrapper.py, line 20 at r13](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MNTxWu02BYTcR2C0UzG:-MNYSQIGBn_ghmhkJJvp:bmatbgm) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/f01439eb0e861dff985b92b9b26b4f35b8811820/hkube_python_wrapper/wrapper/statelessAlgoWrapper.py#L20)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

The user has no way of sending to another flow
</blockquote></details>

user has, we spoke about it
___
*[hkube_python_wrapper/wrapper/statelessAlgoWrapper.py, line 47 at r13](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MNTyKMh-ZoVoW8KKoQ3:-MNXFbIR3JM94JdAMIR3:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/f01439eb0e861dff985b92b9b26b4f35b8811820/hkube_python_wrapper/wrapper/statelessAlgoWrapper.py#L47)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

> ```
> if not (self.originalAlgorithm.get('stop') is None):
> ```
`if self.originalAlgorithm.get('stop')` is much shorter
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-03 08:04 UTC, yehiyam requested changes
> Reviewed 12 of 12 files at r14, 1 of 1 files at r15, 1 of 1 files at r16.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38)* status: all files reviewed, 6 unresolved discussions (waiting on @golanha and @NassiHarel)

___
*[hkube_python_wrapper/codeApi/hkube_api.py, line 23 at r14](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MNb_7QXCzKjR8cFyxR_:-MNb_7QXCzKjR8cFyxRa:b-yoq2vc) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/9c1ce944e78abe099eead09ce4b7fd2a0ca2bcfa/hkube_python_wrapper/codeApi/hkube_api.py#L23)):*
> ```
> sendError
> ```
Is this method used?
___
*[hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, line 69 at r14](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MNbbDDu-stPsk5oWLJd:-MNbbDDu-stPsk5oWLJe:b5iuq9h) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/9c1ce944e78abe099eead09ce4b7fd2a0ca2bcfa/hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py#L69)):*
> ```Python
>                     break
> 
>                 if len(frames) == 3:
> ```

you can destructure `frames` here so you'll have meaningful names later on
___
*[hkube_python_wrapper/communication/zmq/streaming/producer/ZMQProducer.py, line 94 at r14](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MNbbde0CNP2ixYWqqZD:-MNbbde11ll5-4MzKIWD:bcovp83) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/9c1ce944e78abe099eead09ce4b7fd2a0ca2bcfa/hkube_python_wrapper/communication/zmq/streaming/producer/ZMQProducer.py#L94)):*
> ```
> Queu
> ```
Typo
___
*[hkube_python_wrapper/wrapper/statelessAlgoWrapper.py, line 11 at r14](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MNbc0SL-Cod0UmlrQCY:-MNbc0SM2533HuDU5Tfh:bfh9e21) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/9c1ce944e78abe099eead09ce4b7fd2a0ca2bcfa/hkube_python_wrapper/wrapper/statelessAlgoWrapper.py#L11)):*
> ```
> self.threadLocalStorage
> ```
Is this used?


<!-- Sent from Reviewable.io -->

2020-12-03 10:42 UTC, golanha reviewed
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38)* status: 8 of 15 files reviewed, 6 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[hkube_python_wrapper/codeApi/hkube_api.py, line 23 at r14](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MNb_7QXCzKjR8cFyxR_:-MNbnTlF7aMfrElajoQl:b-naft6h) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/9c1ce944e78abe099eead09ce4b7fd2a0ca2bcfa/hkube_python_wrapper/codeApi/hkube_api.py#L23)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

> ```
> sendError
> ```
Is this method used?
</blockquote></details>

You are right, I now moved it to streamingManager
___
*[hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, line 69 at r14](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MNbbDDu-stPsk5oWLJd:-MNbpG5e58yrkI-6Ydja:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/9c1ce944e78abe099eead09ce4b7fd2a0ca2bcfa/hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py#L69)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

you can destructure `frames` here so you'll have meaningful names later on
</blockquote></details>

Done.
___
*[hkube_python_wrapper/communication/zmq/streaming/producer/ZMQProducer.py, line 94 at r14](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MNbbde0CNP2ixYWqqZD:-MNbpqkaDjoNqsTCEVsQ:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/9c1ce944e78abe099eead09ce4b7fd2a0ca2bcfa/hkube_python_wrapper/communication/zmq/streaming/producer/ZMQProducer.py#L94)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

> ```
> Queu
> ```
Typo
</blockquote></details>

Done.
___
*[hkube_python_wrapper/wrapper/statelessAlgoWrapper.py, line 11 at r14](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38#-MNbc0SL-Cod0UmlrQCY:-MNc4mN75PN2CP51iWed:b-tkcd26) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/9c1ce944e78abe099eead09ce4b7fd2a0ca2bcfa/hkube_python_wrapper/wrapper/statelessAlgoWrapper.py#L11)):*
> threadLocalStorage
Oh! this is a good catch.
It seems I had removed important logic, making sure a when you send a message with out a flowName while its in a middle of a flow, it would continue in its flow.
Its now covered in the test. 


<!-- Sent from Reviewable.io -->

2020-12-03 14:33 UTC, yehiyam approved these changes
> Reviewed 7 of 7 files at r17.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/38)* status: all files reviewed, 2 unresolved discussions (waiting on @NassiHarel)



<!-- Sent from Reviewable.io -->

2020-12-03 15:18 UTC, merged